export const afiliadosData = [
  {
    id: 1,
    user: "Prabodhan Fitzgerald",
    email: "Cell",
    location: "Izaiahport",
    status: "Active",
  },
  {
    id: 2,
    user: "Hiro Joyce",
    email: "Cell",
    location: "Strackeside",
    status: "Active",
  },
  {
    id: 3,
    user: "Lloyd Jefferson",
    email: "Cell",
    location: "Texas City",
    status: "Active",
  },
  {
    id: 4,
    user: "Ceiran Mayo",
    email: "Cell",
    location: "Lake Esmeralda",
    status: "Active",
  },
  {
    id: 5,
    user: "Thumbiko James",
    email: "Cell",
    location: "East Paige",
    status: "Suspended",
  },
  {
    id: 6,
    user: "Maria Garcia",
    email: "Cell",
    location: "New York",
    status: "Active",
  },
  {
    id: 7,
    user: "John Smith",
    email: "Cell",
    location: "Los Angeles",
    status: "Active",
  },
  {
    id: 8,
    user: "Ana Martinez",
    email: "Cell",
    location: "Miami",
    status: "Suspended",
  },
  {
    id: 9,
    user: "Carlos Rodriguez",
    email: "Cell",
    location: "Chicago",
    status: "Active",
  },
  {
    id: 10,
    user: "Sofia Lopez",
    email: "Cell",
    location: "Houston",
    status: "Active",
  },
  {
    id: 11,
    user: "Diego Hernandez",
    email: "Cell",
    location: "Phoenix",
    status: "Active",
  },
  {
    id: 12,
    user: "Isabella Torres",
    email: "Cell",
    location: "Philadelphia",
    status: "Suspended",
  },
  {
    id: 13,
    user: "Miguel Ramirez",
    email: "Cell",
    location: "San Antonio",
    status: "Active",
  },
];